services:
  - type: web
    name: taskmaster
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    plan: free
    region: oregon
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: app.py
